name: EAS Build Android

on:
    push:
      branches:
        - 'preview/**'
        - 'release/**'

jobs:
    build:
        runs-on: ubuntu-latest

        strategy:
            matrix:
                node-version: [20.x]

        steps:
          - uses: actions/checkout@v3

          - name: Use Node.js ${{ matrix.node-version }}
            uses: actions/setup-node@v4
            with:
              node-version: ${{ matrix.node-version }}

          - name: Set Environment Variable
            run: |
              if [[ "${GITHUB_REF#refs/heads/}" =~ ^release.* ]]; then
                  echo "TARGET=production" >> $GITHUB_ENV
              else
                  echo "TARGET=preview" >> $GITHUB_ENV
              fi

          - name: Install dependencies
            run: npm install

          - name: Install EAS CLI
            run: npm install -g eas-cli

          - name: EAS Build Android
            run: eas build --platform android --profile $TARGET --non-interactive
            env:
              EXPO_TOKEN: ${{ secrets.EXPO_TOKEN }}
